name: Build

on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
          # git config --global url."https://github.com/".insteadOf "git@github.com:"
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1


      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v1.0.5


      - name: Nuget Restore SharpHound3
        run: nuget restore $Env:GITHUB_WORKSPACE\SharpHound3\SharpHound3.sln

      - name: Build SharpHound3
        run: |
          cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
          .\MSBuild.exe $Env:GITHUB_WORKSPACE\SharpHound3\SharpHound3\SharpHound3.csproj /property:Configuration=Release

      - uses: actions/upload-artifact@master
        with:
          name: SharpHound3
          path: SharpHound3\SharpHound3\bin\Release\SharpHound.exe

      - name: Nuget Restore Rubeus
        run: nuget restore $Env:GITHUB_WORKSPACE\Rubeus\Rubeus.sln

      - name: Build Rubeus
        run: |
          cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
          .\MSBuild.exe $Env:GITHUB_WORKSPACE\Rubeus\Rubeus\Rubeus.csproj /property:Configuration=Release

      - uses: actions/upload-artifact@master
        with:
          name: Rubeus
          path: Rubeus\Rubeus\bin\Release\Rubeus.exe

      - name: Nuget Restore SafetyKatz
        run: nuget restore $Env:GITHUB_WORKSPACE\SafetyKatz\SafetyKatz.sln

      - name: Build SafetyKatz
        run: |
          cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
          .\MSBuild.exe $Env:GITHUB_WORKSPACE\SafetyKatz\SafetyKatz\SafetyKatz.csproj /property:Configuration=Release

      - uses: actions/upload-artifact@master
        with:
          name: SafetyKatz
          path: SafetyKatz\SafetyKatz\bin\Release\SafetyKatz.exe



      - name: Nuget Restore Seatbelt
        run: nuget restore $Env:GITHUB_WORKSPACE\Seatbelt\Seatbelt.sln

      - name: Build Seatbelt
        run: |
          cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
          .\MSBuild.exe $Env:GITHUB_WORKSPACE\Seatbelt\Seatbelt\Seatbelt.csproj /property:Configuration=Release

      - uses: actions/upload-artifact@master
        with:
          name: Seatbelt
          path: Seatbelt\Seatbelt\bin\Release\Seatbelt.exe



      - name: Nuget Restore SharpDPAPI
        run: nuget restore $Env:GITHUB_WORKSPACE\SharpDPAPI\SharpDPAPI.sln

      - name: Build SharpDPAPI
        run: |
          cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
          .\MSBuild.exe $Env:GITHUB_WORKSPACE\SharpDPAPI\SharpDPAPI\SharpDPAPI.csproj /property:Configuration=Release

      - uses: actions/upload-artifact@master
        with:
          name: SharpDPAPI
          path: SharpDPAPI\SharpDPAPI\bin\Release\SharpDPAPI.exe



      - name: Nuget Restore SharpUp
        run: nuget restore $Env:GITHUB_WORKSPACE\SharpUp\SharpUp.sln

      - name: Build SharpUp
        run: |
          cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
          .\MSBuild.exe $Env:GITHUB_WORKSPACE\SharpUp\SharpUp\SharpUp.csproj /property:Configuration=Release

      - uses: actions/upload-artifact@master
        with:
          name: SharpUp
          path: SharpUp\SharpUp\bin\Release\SharpUp.exe


